---
title: "Reform analyses"
author: "Don Boyd and Matt Jensen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook: 
    df_print: paged
    fig_height: 6
    fig_width: 8
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: console
---

# SETUP
```{r setup, eval=TRUE, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}

# note that eval=TRUE unless set to FALSE

knitr::opts_chunk$set(eval=TRUE, include=FALSE, echo = FALSE)
options(width = 150)

# usethis::use_github()

```

```{r libraries}
library(tidyverse)
options(tibble.print_max = 80, tibble.print_min = 80) # if more than 60 rows, print 60 - enough for states
library(arrow)

# devtools::install_github("tidyverse/googlesheets4")
library(googlesheets4)

library(kableExtra)
library(btools)
library(gt)
library(knitr)

library(maps)
# https://cran.r-project.org/web/packages/usmap/vignettes/mapping.html
library(usmap)
library(gridExtra)
library(RcppRoll)
library(ggrepel)
library(ggbreak)
library(patchwork)
library(RColorBrewer)

```

```{r locations}
# SALTDIR <- r"(E:\pufanalysis_outputs\salt_tc3.2.1\)"
WEIGHTDIR <- r"(E:\puf_analysis_inputs\weights\)"  
REFDIR <- r"(E:\pufanalysis_outputs\reform_outputs\)"
PUFDIR <- r"(E:\data\puf_files\puf_csv_related_files\PSL\2021-07-20\)"

```


```{r constants}
BASEYEAR <- 2017
DATAYEAR <- 2022
REWTVAR <- paste0("REWT", DATAYEAR)

geos <- c(state.abb, "other")

# df with upper bound of open intervals (does not include endpoint on right)
agi_stubs <- tribble(~agicut, ~agilabel,
                     -Inf, "Negative",
                     1, "Under $1",
                     25e3, "$1 to < $25k",
                     50e3, "$25k < 50k",
                     75e3, "$50k < 75k",
                     100e3, "$75k < $100k",
                     200e3, "$100k < $200k",
                     500e3, "$200k < $500k",
                     1e6, "$500k < $1m",
                     Inf, "$1m+")


```

```{r utility_functions}
get_stname <- function(stabbr){
  allgeos <- c("US", geos)
  allnames <- c("United States", state.name, "Other")
  allnames[match(stabbr, allgeos)]
}
```

# ONETIME DATA PREPARATION

```{r ONETIME_prepare_usreweights}
# create state weights for a different year; we want
# RECID,filer2017,WT2017,WT2021,REWT2017, -- plus REWT2021, REWT2022, etc.

# get my 2017 state weights
stweights2017 <- read_csv(paste0(WEIGHTDIR, 'allweights2017_geo_restricted.csv')) %>%
  mutate(RECID=as.integer(pid + 1))

# get official national weights
pufweights1 <- read_csv(paste0(PUFDIR, "puf_weights.csv"))

pufweights2 <- pufweights1 %>%
  mutate(RECID=row_number())

pufweights3 <- pufweights2 %>%
  mutate(across(starts_with("WT"), ~ .x / 100)) %>%
  left_join(stweights2017 %>%
              select(RECID, REWT2017=weight),
            by="RECID") %>%
  mutate(filer2017=!is.na(REWT2017),
         # fill in REWT2017 with WT2017 where REWT2017 is missing
         REWT2017=ifelse(filer2017, REWT2017, WT2017)) %>%
  select(RECID, filer2017, REWT2017, everything())
count(pufweights3, filer2017)

pwlong <- pufweights3 %>%
  pivot_longer(-c(RECID, filer2017, WT2017, REWT2017), names_to="wtyear", values_to = "pufweight") %>%
  group_by(filer2017, wtyear) %>%
  mutate(ratio=sum(pufweight) / sum(WT2017),
         futureweight=ifelse(filer2017, REWT2017 * ratio, pufweight))

# flip the file so that we have the new weights
usreweights <- pwlong %>%
  filter(wtyear %in% paste0("WT", 2018:2031)) %>%
  select(RECID, filer2017, WT2017, REWT2017, wtyear, futureweight) %>%
  mutate(wtyear=paste0("RE", wtyear)) %>%
  pivot_wider(names_from = wtyear, values_from = futureweight)

write_csv(usreweights, paste0(WEIGHTDIR, "usreweights.csv"))

# compare the reweights for 2021 to what I previously had for 2021
w2021 <- read_csv(paste0(WEIGHTDIR, "weights2021.csv")) %>% select(-WT2021)
check <- bind_rows(w2021 %>% mutate(type="prior"),
                   usreweights %>% 
                     select(all_of(names(w2021))) %>%
                     mutate(type="new"))

check2 <- check %>%
  pivot_longer(contains("WT")) %>%
  pivot_wider(names_from = type) %>%
  filter(abs(new - prior) > 0.1) # we want this to be empty
  
# calculate rough weights for the data year REWT2021
# apply a single ratio to all 2017 filer weights, calculated as
# the sum of 2022 2017 filer weights
# pwratio = weights2021.loc[weights2021.filer2017==True, 'WT2021'].sum() \
#     / weights2021.loc[weights2021.filer2017==True, 'WT2017'].sum()


# original python code
# PWDIR = '/media/don/data/puf_files/puf_csv_related_files/PSL/2021-07-20/'
# pufweights = pd.read_csv(PWDIR + 'puf_weights.csv')
# # create a RECID column
# pufweights['RECID'] = np.arange(pufweights.shape[0]) + 1
# pufweights.head()
# 
# # bring in my 2017 weights as REWT2017
# weights2017 = pd.read_csv(WDIR + 'allweights2017_geo_restricted.csv') # 227766, filers only
# weights2017['RECID'] = weights2017.pid + 1
# 
# weights2021 = pd.merge(pufweights.loc[:, ['RECID', 'WT2017', 'WT2021']], \
#     weights2017.loc[:, ['RECID', 'weight']].rename(columns={'weight': 'REWT2017'}), \
#         how='left', on='RECID')
# 
# # convert puf weights to decimal weights
# weights2021.loc[:, ['WT2017', 'WT2021']] = weights2021.loc[:, ['WT2017', 'WT2021']] / 100.
# 
# # create filer2017 indicator for missing/nonmissing
# weights2021['filer2017'] = weights2021.REWT2017.notna()
# weights2021.filer2017.value_counts()  # good
# 
# # fill in REWT2017 with WT2017 where REWT2017 is missing
# weights2021.loc[weights2021.filer2017==False, 'REWT2017'] = \
#     weights2021.loc[weights2021.filer2017==False, 'WT2017']
# 
# # calculate rough 2021 weights as REWT2021
# # apply a single ratio to all 2017 filer weights
# pwratio = weights2021.loc[weights2021.filer2017==True, 'WT2021'].sum() \
#     / weights2021.loc[weights2021.filer2017==True, 'WT2017'].sum()
# 
# # multiply 2017 filer reweights by the fixed ratio
# weights2021.loc[weights2021.filer2017==True, 'REWT2021'] = \
#     weights2021.loc[weights2021.filer2017==True, 'REWT2017'] * pwratio
# weights2021.loc[weights2021.filer2017==False, 'REWT2021'] = \
#     weights2021.loc[weights2021.filer2017==False, 'WT2021']
# 
# weights2021 = weights2021.loc[:, ['RECID', 'filer2017', 'WT2017', 'WT2021', 'REWT2017', 'REWT2021']]

```

# DATA PREPARATION

```{r get_reform_descriptions}
url <- "https://docs.google.com/spreadsheets/d/1aEQlAV2I9HSnG00TEmjCE_Sj44vqLWIrXwbW0DTtID0/edit#gid=0"
reform_descriptions <- read_sheet(url)
reform_descriptions

```


```{r prepare_state_weights, include=FALSE}
# get my all-years national reweights 
#   assumes same growth in returns post 2017 as in puf weights
usreweights <- read_csv(paste0(WEIGHTDIR, 'usreweights.csv')) 
glimpse(reusweights)

usreweights %>%
  select(-c(REWT2024:REWT2030)) %>%
  group_by(filer2017) %>%
  summarise(across(-c(RECID), ~ sum(.x))) %>%
  add_row() %>%
  mutate(across(-filer2017, ~ifelse(is.na(filer2017), sum(.x, na.rm=TRUE), .x)))

# get my 2017 state reweights
stweights2017 <- read_csv(paste0(WEIGHTDIR, 'allweights2017_geo_restricted.csv')) %>%
  mutate(RECID=as.integer(pid + 1))
# glimpse(stweights2017)

# create state shares from my national and state weights
stshares <- stweights2017 %>%
  mutate(across(all_of(geos), ~ .x / geoweight_sum))
glimpse(stshares)

# do all shares add to 1?
check <- stshares %>%
  pivot_longer(cols=all_of(geos)) %>%
  group_by(RECID) %>%
  summarise(sum=sum(value), .groups="drop")
check %>% filter(abs(sum - 1) > 1e-6) # we want this to be empty

# create state weights
stweights <- usreweights %>%
  select(RECID, filer2017, US=all_of(REWTVAR)) %>%
  left_join(stshares %>% select(RECID, all_of(geos)), by="RECID") %>%
  mutate(across(all_of(geos), ~ .x * US))
glimpse(stweights) 
# note that this gives NA state weights for nonfilers; eventually need nonfiler weights

# verify that state weights sum to national weights for each record
check <- stweights %>%
  filter(filer2017) %>%
  select(RECID, US, all_of(geos)) %>%
  pivot_longer(-c(RECID, US)) %>%
  group_by(RECID, US) %>%
  summarise(wtsum=sum(value), .groups="drop") %>%
  mutate(diff=wtsum - US,
         pdiff=diff / US * 100)
# quantile(check$pdiff)  # should be very near zero

# Are any weights negative??
# summary(stweights)  # no

```


```{r define_tcvars}
tcvars <- c("RECID", "c00100", "e00200",  "standard", "c04470", "c18300",
          "iitax", "combined",
          "expanded_income", "benefit_value_total")
```


```{r get_baseline}

basedf <- read_parquet(paste0(REFDIR, "baseline.parquet"),
                       col_select = all_of(tcvars)) %>%
  mutate(agibase=c00100, 
         taxstatus=ifelse(combined >= 0, "taxpayer", "negtax"),
         numret=1, type="base",
         refnum=0)
# postaxind indicates that a filer had positive tax in the base analysis, as we will compute
# some averages for this subset of filers

```


```{r get_reform}
# reform1_beh.parquet
get_reformdf <- function(refnum){
  reform_file <- paste0("reform", refnum, ".parquet")
  reformdf <- read_parquet(paste0(REFDIR, reform_file),  # OLD: reform2021.parquet
                       col_select = all_of(tcvars)) %>%
    left_join(basedf %>% select(RECID, agibase, numret, taxstatus), by="RECID") %>%
    mutate(type="reform", refnum=!!refnum)
}
# reformdf <- get_reformdf(1)

stack_files <- function(basedf, reformdf){
  stack <- bind_rows(basedf, reformdf) %>%
    left_join(stweights, by="RECID") %>%
    mutate(stub=cut(agibase, 
                  agi_stubs$agicut, 
                  labels=agi_stubs$agilabel[-1], include.lowest = TRUE, right=FALSE),
           stubnum=as.integer(stub),
           xpinc=expanded_income - benefit_value_total,
           dispinc=xpinc - combined) %>%
    select(-expanded_income, -benefit_value_total)
}
# stack <- stack_files(basedf, reformdf)

weight_stack <- function(stack){
  wstack <- stack %>%
    mutate(across(c(US, all_of(geos)),
                  list(numret=~.x,
                       agi=~.x * c00100,
                       xpinc=~.x * xpinc,
                       dispinc=~.x * dispinc,
                       combined=~.x * combined,
                       iitax=~.x * iitax,
                       salt=~.x * c18300))) %>%
  select(-c(US, all_of(geos)))
}
# wstack <- weight_stack(stack)

get_wsums <- function(wstack){
  wsums <- wstack %>%
    filter(filer2017) %>%
    select(-c(RECID, filer2017, numret, 
              c00100, e00200, c18300, c04470, standard, 
              combined, iitax, agibase, xpinc, dispinc)) %>%
  group_by(type, refnum, taxstatus, stubnum, stub) %>%
  summarise(across(.cols=everything(), sum), .groups="drop")
}
# wsums <- get_wsums(wstack)

get_filersums <- function(wsums){
  
  wsums_long <- wsums %>%
    pivot_longer(-c(type, refnum, taxstatus, stubnum, stub),
                 values_to = "wtdsum")

  # add in the all-stubs sum for each group
  stubsums <- wsums_long %>%
    group_by(type, refnum, taxstatus, name) %>%
    summarise(wtdsum=sum(wtdsum, na.rm=TRUE), .groups="drop") %>%
    mutate(stubnum=0, stub="Total")
  
  allsums1 <- wsums_long %>%
    mutate(stub=as.character(stub)) %>%
    bind_rows(stubsums) %>%
    separate(name, into=c("stabbr", "variable")) %>%
    arrange(type, refnum, taxstatus, stabbr, variable, stubnum)
  
  # get an "all returns" category
  filersums <- allsums1 %>%
    group_by(type, refnum, stabbr, variable, stub, stubnum) %>%
    summarise(wtdsum=sum(wtdsum), .groups="drop") %>%
    mutate(taxstatus="allfilers") %>%
    bind_rows(allsums1) %>%
    arrange(type, taxstatus, stabbr, variable)
  
  filersums
}
# filersums <- get_filersums(wsums)
  
get_xpinc <- function(filersums){
  # create an "xpincxreform" concept - xpanded income minus the tax change
  # for base it will be xpinc, but for reform it will be xpinc - iitax
  xpincxreform <- filersums %>%
    filter(variable %in% c("xpinc", "iitax")) %>%
    pivot_wider(names_from = variable, values_from=wtdsum) %>%
    group_by(taxstatus, stabbr, stub, stubnum) %>%
    mutate(basetax=iitax[type=="base"],
           basexpinc=xpinc[type=="base"],
           xpincxreform=ifelse(type=="base", 
                               xpinc, 
                               basexpinc + basetax - iitax)) %>%
    ungroup %>%
    arrange(taxstatus, stabbr, stubnum, stub, type)
  
  # convert back to long
  xpinc <- xpincxreform %>%
    select(type, refnum, stabbr, stub, stubnum, taxstatus, xpincxreform) %>%
    pivot_longer(xpincxreform, names_to = "variable", values_to = "wtdsum")
  
  xpinc
}
# xpinc <- get_xpinc(filersums)


get_changes <- function(filersums, xpinc){
  changes1 <- bind_rows(filersums, xpinc) %>%
    group_by(type, refnum, taxstatus, stabbr, stub, stubnum) %>%
    mutate(numret=wtdsum[variable=="numret"],
           avgval=wtdsum / numret) %>%
    ungroup

  changes2 <- changes1 %>%
    select(-refnum) %>%  # leave this off until I redefine it
    pivot_longer(c(wtdsum, numret, avgval), names_to = "measure") %>%
    pivot_wider(names_from=type, values_from=value) %>%
    mutate(change=reform - base,
           pchange=ifelse(base > 0, change / base, NA_real_))

  # put US values on the file
  changes <- changes2 %>%
    left_join(changes2 %>% 
                filter(stabbr=="US") %>% 
                select(taxstatus, stubnum, stub, variable, measure, 
                       us_base=base, us_reform=reform, us_change=change,
                       us_pchange=pchange),
              by=c("taxstatus", "stubnum", "stub", "variable", "measure"))
  
  changes
}
changes <- get_changes(filersums, xpinc)

# count(changes, stabbr) # 52: US, 50 states, other
# count(changes, variable)
# count(changes, stubnum, stub)  # no negtax values for the highest income ranges
# count(changes, taxstatus)
# count(changes, measure)

```


```{r organize_results}
get_usiitax <- function(changes){
  stiitax <- changes %>%
    filter(measure %in% c("wtdsum", "avgval"),
           variable %in% c("iitax", "dispinc")) %>%
    select(variable, stabbr, taxstatus, stubnum, stub, measure,
           base, reform, change, pchange) %>%
    pivot_longer(-c(stabbr, taxstatus, stubnum, stub, variable, measure)) %>%
    unite("name", c(measure, name)) %>%
    pivot_wider() %>%
    mutate(junk="") %>%
    arrange(stubnum) %>%
    select(variable, stabbr, taxstatus, stubnum, stub,
           starts_with("wtdsum"), junk, starts_with("avg")) %>%
    filter(variable=="iitax") %>%
    select(-variable)

  usiitax <- stiitax %>%
    filter(stabbr=="US") %>%
    select(taxstatus, stubnum, stub, 
           starts_with("wtdsum"), junk, starts_with("avg"))
  
  usiitax
}

get_uscombined <- function(changes){
  stcombined <- changes %>%
    filter(measure %in% c("wtdsum", "avgval"),
           variable %in% c("combined", "dispinc")) %>%
    select(variable, stabbr, taxstatus, stubnum, stub, measure,
           base, reform, change, pchange) %>%
    pivot_longer(-c(stabbr, taxstatus, stubnum, stub, variable, measure)) %>%
    unite("name", c(measure, name)) %>%
    pivot_wider() %>%
    mutate(junk="") %>%
    arrange(stubnum) %>%
    select(variable, stabbr, taxstatus, stubnum, stub,
           starts_with("wtdsum"), junk, starts_with("avg")) %>%
    filter(variable=="combined") %>%
    select(-variable)

  uscombined <- stcombined %>%
    filter(stabbr=="US") %>%
    select(taxstatus, stubnum, stub, 
           starts_with("wtdsum"), junk, starts_with("avg"))
  
  uscombined
}

```



```{r test}
refnum <- 1
reformdf <- get_reformdf(refnum)  # return-level data
stack <- stack_files(basedf, reformdf)  # return-level data
wstack <- weight_stack(stack)  # return-level data
wsums <- get_wsums(wstack)  # summary data
filersums <- get_filersums(wsums) # summary data
xpinc <- get_xpinc(filersums)
changes <- get_changes(filersums, xpinc)
usiitax <- get_usiitax(changes)
uscombined <- get_uscombined(changes)


dim(wsums) # each col is weighted value for variable, state
# OLD: 36 rows: type 2, wtype 2, stubs 9, each col is weighted value for variable, state
glimpse(wsums)
count(wsums, type) # base, reform
count(wsums, stubnum, stub) # 9 stubs
count(wsums, refnum)
count(wsums, type, stubnum, stub) # 18 records
names(wsums)
ns(wsums)

wsums %>% filter(wtype=="REWT2021", type=="base") %>% select(1:7)

dim(wstack)
glimpse(wstack) # ~500k recs, variables are weighted
ns(wstack)

summary(filersums)
count(filersums, type)
count(filersums, taxstatus)
count(filersums, stubnum, stub)
count(filersums, variable)
count(filersums, stabbr)

```

```{r get_all}
get_all <- function(refnum) {
  reform_name <- reform_descriptions %>%
  filter(number==refnum) %>% .$description
  
  reformdf <- get_reformdf(refnum)  # return-level data
  stack <- stack_files(basedf, reformdf)  # return-level data
  wstack <- weight_stack(stack)  # return-level data
  wsums <- get_wsums(wstack)  # summary data
  filersums <- get_filersums(wsums) # summary data
  xpinc <- get_xpinc(filersums)
  changes <- get_changes(filersums, xpinc)
  usiitax <- get_usiitax(changes)
  uscombined <- get_uscombined(changes)
  
  results <- list()
  results$refnum <- refnum
  results$reform_name <- reform_name
  results$changes <- changes
  results$usiitax <- usiitax
  results$uscombined <- uscombined
  results
  }

# lcheck <- get_all(2)
# lcheck$refnum
# lcheck$reform_name
# lcheck$uscombined
```


# TABLES AND GRAPHS

```{r}

```

## National analysis

```{r national_tab_functions}

tab_combined <- function(uscombined, reform_name){
  tabdata <- uscombined %>%
    filter(taxstatus=="allfilers") %>%
    select(-taxstatus)
  
  dcols <- c("wtdsum_base", "wtdsum_reform", "wtdsum_change", "avgval_base",
             "avgval_reform", "avgval_change")
  pcols <- c("wtdsum_pchange", "avgval_pchange")

  subt <- "Aggregate and average tax liabilities by income group"

  tab <- tabdata %>%
    select(-stubnum) %>%
    gt()  %>%  
    tab_header(
      title = paste0(reform_name, " compared to current 2022 law"),
      subtitle = subt
    ) %>%
    cols_label(
      stub = "",
      wtdsum_base = "2022 current law",
      wtdsum_reform = reform_name,
      wtdsum_change = html("$ change: <br>Reform minus<br>current law"),
      wtdsum_pchange = html("% change: <br>Reform versus<br>current law"),
      
      junk="",
      
      avgval_base = "2022 current law",
      avgval_reform = reform_name,
      avgval_change = html("$ change: <br>Reform minus<br>current law"),
      avgval_pchange = html("% change: <br>Reform versus<br>current law")
      ) %>%
    
    fmt_currency(
      columns = all_of(str_subset(dcols, "wtdsum")),
      rows=1,
      decimals = 1,
      scale_by = 1e-9,
      suffixing = FALSE
    )   %>%
    fmt_currency(
      columns = all_of(str_subset(dcols, "avgval")),
      rows=1,
      decimals = 0,
      scale_by = 1,
      suffixing = FALSE
    )   %>%
    fmt_number(
      columns = all_of(str_subset(dcols, "wtdsum")),
      rows=2:nrow(tabdata),
      decimals = 1,
      scale_by = 1e-9,
      suffixing = FALSE
    ) %>%
    fmt_number(
      columns = all_of(str_subset(dcols, "avgval")),
      rows=2:nrow(tabdata),
      decimals = 0,
      scale_by = 1,
      suffixing = FALSE
    ) %>%
    
    fmt_percent(
      columns = all_of(pcols),
      decimals = 1
    ) %>%
    fmt_missing(
      columns=all_of(pcols),
      missing_text = "--") %>%
    tab_style(
      style = list(
        cell_fill(color = "#f7f7f7")
      ),
      locations = cells_body(
        rows = seq(1, nrow(tabdata), 2)
        )
    ) %>%
    tab_spanner(
      label = html("Aggregate impact in $ billions"),
      columns = c("wtdsum_base", "wtdsum_reform", "wtdsum_change", "wtdsum_pchange",)
    ) %>%
    tab_spanner(
      label = html("Average impact over all returns, in dollars"),
      columns = c("avgval_base", "avgval_reform", "avgval_change", "avgval_pchange")
    ) %>%
    cols_width(
      stub ~ px(150),
      starts_with("wtd") ~ px(100),
      junk ~ px(20),
      starts_with("avg") ~ px(100),
      everything() ~ px(60)
    )
  
  tab
}


save_combined <- function(tab, refnum){
  # configure save settings for wide table
  folder_name <- paste0("reform", refnum)
  dir.create(file.path(here::here("results", folder_name)), showWarnings = FALSE)
  fname <- paste0(folder_name, "_USImpact_combined_table.png")
  # zoom 2 default
  gtsave(tab, fname, path = here::here("results", folder_name), zoom=2, vwidth=1500) 
}


```


```{r loop_national}
for(refnum in 1:13){
  print(paste0("Reform #: ", refnum))
  results <- get_all(refnum)
  tab <- tab_combined(results$uscombined, results$reform_name)
  save_combined(tab, refnum)
}

```



```{r uscombined_table, include=TRUE}

reform_name <- reform_descriptions %>%
  filter(number==refnum) %>% .$description

# for this first US table we want all filers
tabdata <- uscombined %>%
  filter(taxstatus=="allfilers") %>%
  select(-taxstatus)

dcols <- c("wtdsum_base", "wtdsum_reform", "wtdsum_change", "avgval_base", "avgval_reform", "avgval_change")
pcols <- c("wtdsum_pchange", "avgval_pchange")

subt <- "Aggregate and average tax liabilities by income group"

tab <- tabdata %>%
  select(-stubnum) %>%
  gt()  %>%  
  tab_header(
    title = paste0(reform_name, " compared to current 2022 law"),
    subtitle = subt
  ) %>%
  cols_label(
      stub = "",
      wtdsum_base = "2022 current law",
      wtdsum_reform = reform_name,
      wtdsum_change = html("$ change: <br>Reform minus<br>current law"),
      wtdsum_pchange = html("% change: <br>Reform versus<br>current law"),
      
      junk="",
      
      avgval_base = "2022 current law",
      avgval_reform = reform_name,
      avgval_change = html("$ change: <br>Reform minus<br>current law"),
      avgval_pchange = html("% change: <br>Reform versus<br>current law")
    ) %>%
  
  fmt_currency(
    columns = all_of(str_subset(dcols, "wtdsum")),
    rows=1,
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  )   %>%
  fmt_currency(
    columns = all_of(str_subset(dcols, "avgval")),
    rows=1,
    decimals = 0,
    scale_by = 1,
    suffixing = FALSE
  )   %>%
  fmt_number(
    columns = all_of(str_subset(dcols, "wtdsum")),
    rows=2:nrow(tabdata),
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  ) %>%
  fmt_number(
    columns = all_of(str_subset(dcols, "avgval")),
    rows=2:nrow(tabdata),
    decimals = 0,
    scale_by = 1,
    suffixing = FALSE
  ) %>%
  
  fmt_percent(
    columns = all_of(pcols),
    decimals = 1
  ) %>%
  fmt_missing(
    columns=all_of(pcols),
    missing_text = "--") %>%
  tab_style(
    style = list(
      cell_fill(color = "#f7f7f7")
    ),
    locations = cells_body(
      rows = seq(1, nrow(tabdata), 2)
      )
  ) %>%
  tab_spanner(
    label = html("Aggregate impact in $ billions"),
    columns = c("wtdsum_base", "wtdsum_reform", "wtdsum_change", "wtdsum_pchange",)
  ) %>%
  tab_spanner(
    label = html("Average impact over all returns, in dollars"),
    columns = c("avgval_base", "avgval_reform", "avgval_change", "avgval_pchange")
  ) %>%
  cols_width(
    stub ~ px(150),
    starts_with("wtd") ~ px(100),
    junk ~ px(20),
    starts_with("avg") ~ px(100),
    everything() ~ px(60)
  )

tab

# configure save settings for wide table
folder_name <- paste0("reform", refnum)
dir.create(file.path(here::here("results", folder_name)), showWarnings = FALSE)
fname <- paste0(folder_name, "_USImpact_combined_table.png")
# zoom 2 default
gtsave(tab, fname, path = here::here("results", folder_name), zoom=2, vwidth=1500)  


```






```{r rows.print=20}
# data3 is the key result

str(knitr::opts_chunk$get()) # default chunk options
# opts_current$get()
filersums  # "type"     "wtype"    "stubnum"  "stub"     "stabbr"   "variable" "value"  
count(filersums, variable)

# create an "xpincxreform" concept - xpanded income minus the tax change
# for base it will be xpinc, but for reform it will be xpinc - iitax
xpincxreform <- filersums %>%
  filter(variable %in% c("xpinc", "iitax")) %>%
  pivot_wider(names_from = variable) %>%
  group_by(taxstatus, wtype, stabbr, stub, stubnum) %>%
  mutate(basetax=iitax[type=="base"],
         basexpinc=xpinc[type=="base"],
         xpincxreform=ifelse(type=="base", 
                             xpinc, 
                             basexpinc + basetax - iitax)) %>%
  ungroup %>%
  arrange(taxstatus, wtype, stabbr, stubnum, stub, type)
  
xpincxreform %>% filter(stabbr=="NY", wtype=="REWT2021", stubnum >= 5, taxstatus=="taxpayer")

# convert back to long
xpincxrlong <- xpincxreform %>%
  select(type, wtype, stabbr, stub, stubnum, taxstatus, xpincxreform) %>%
  pivot_longer(xpincxreform, names_to = "variable")


# create a file that has number of returns, value, and average value for each rec, with reweights
data1 <- bind_rows(filersums, xpincxrlong) %>%
  filter(wtype=="REWT2021") %>%
  rename(wtdsum=value) %>%
  group_by(type, wtype, taxstatus, stabbr, stub, stubnum) %>%
  mutate(numret=wtdsum[variable=="numret"],
         avgval=wtdsum / numret) %>%
  ungroup


data1 %>%
  filter(stabbr=="MS", stubnum==0, variable=="iitax")

data1 %>%
  filter(stabbr=="NY", stubnum==0, variable=="xpinc")

data1 %>%
  filter(stabbr=="NY", stubnum==0, variable=="xpincxreform")

data2 <- data1 %>%
  pivot_longer(c(wtdsum, numret, avgval), names_to = "measure") %>%
  pivot_wider(names_from=type, values_from=value) %>%
  mutate(change=reform - base,
         pchange=ifelse(base > 0, change / base, NA_real_))

data2 %>%
  filter(stabbr=="MS", stubnum==0, variable=="iitax")

data2 %>%
  filter(stabbr=="NY", stubnum==0, variable=="xpincxreform")

data3 <- data2 %>%
  left_join(data2 %>% 
              filter(stabbr=="US") %>% 
              select(wtype, taxstatus, stubnum, stub, variable, measure, 
                     us_base=base, us_reform=reform, us_change=change, us_pchange=pchange),
            by=c("wtype", "taxstatus", "stubnum", "stub", "variable", "measure"))


data3 %>% filter(stabbr=="MS", stubnum==0, variable=="iitax")
data3 %>% filter(stabbr=="MS", stubnum==0, variable=="dispinc")


```





```{r reforms}
resdir <- "results_tc3.2.1"

runtypes <- c("repeal", "cap72500", "cap80000")
reform_names <- c("SALT cap repealed", "SALT cap raised to $72,500", "SALT cap raised to $80,000")

runnum <- 3
reform <- runtypes[runnum]
reform_name <- reform_names[runnum]
runresults <- paste0("results_tc3.2.1/", runtypes[runnum])

```


```{r comp_revloss_shares}
# reduce the revenue loss
# make it somewhat less concentrated among the highest income households
# spread the tax revenue reduction more broadly across the states (very slightly)

tab <- "USImpact_billions_table_data.csv"
revloss <- bind_rows(read_csv(here::here(resdir, "repeal", tab)) %>%
                       mutate(type="repeal"),
                     read_csv(here::here(resdir, reform, tab)) %>%
                       mutate(type="reform"))

tabdata <- revloss %>%
  select(stub, wtdsum_change, change_share, type) %>%
  pivot_wider(names_from = type,
              values_from = c(wtdsum_change, change_share)) %>%
  mutate(change_change=wtdsum_change_reform - wtdsum_change_repeal,
         share_change=change_share_reform - change_share_repeal) %>%
  select(stub, 
         wtdsum_change_repeal, wtdsum_change_reform, change_change,
         change_share_repeal, change_share_reform, share_change)
tabdata  

dcols <- c("wtdsum_change_repeal", "wtdsum_change_reform", "change_change")
pcols <- c("change_share_repeal", "change_share_reform") #, "share_change")
ref <- html("SALT cap<br>raised to<br>$80,000")
tab <- tabdata %>%
  select(-share_change) %>%
  gt() %>%  
  tab_header(
    title = "Impact of raising the SALT cap versus full cap repeal",
    subtitle = paste0("Baseline is 2021 current law")
  ) %>%
  tab_spanner(label="Billions of dollars", 
              columns=c(wtdsum_change_repeal, wtdsum_change_reform, change_change)) %>%
  tab_spanner(label="Percentage", 
              columns=c(change_share_repeal, change_share_reform)) %>%
  cols_label(
      stub = "",
      wtdsum_change_repeal = "Full cap repeal",
      wtdsum_change_reform = ref,
      change_change = html("$ change: <br>Reform minus<br>full cap repeal"),
      change_share_repeal="Full cap repeal",
      change_share_reform=ref
      # share_change = html("change in % share of national impact")
    ) %>%
  fmt_currency(
    columns = all_of(dcols),
    rows=1,
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  ) %>%
  fmt_number(
    columns = all_of(dcols),
    rows=2:nrow(tabdata),
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  ) %>%
  fmt_percent(
    columns = all_of(pcols),
    decimals = 1
  )
tab
# gtsave(tab, "USImpactReformVsRepeal_table.png", path = here::here(runresults), zoom=1.5, vwidth=1500)  # zoom 2 default
# gtsave(tab, "USImpactReformVsRepeal_table.png", path = here::here(runresults), zoom=2, vwidth=1500) 
gtsave(tab, "USImpactReformVsRepeal_table.png", path = here::here(runresults)) 
write_csv(tabdata, here::here(runresults, "USImpactReformVsRepeal_table_data.csv"))


```


```{r comp_states, rows.print=30}

tab <- "states_detailed_table_data.csv"
revloss_states <- bind_rows(read_csv(here::here(resdir, "repeal", tab)) %>%
                       mutate(type="repeal"),
                     read_csv(here::here(resdir, reform, tab)) %>%
                       mutate(type="reform"))

tab1 <- revloss_states %>%
  select(stname, totchange, share, type) %>%
  pivot_wider(names_from = type,
              values_from = c(totchange, share)) %>%
  arrange(totchange_reform) %>%
  mutate(group = case_when(stname=="United States" ~ "United States",
                           row_number() <= 11 ~ "Top 10 states",
                           TRUE ~ "Remaining states"))

tab2 <- tab1 %>%
  filter(stname != "United States") %>%
  group_by(group) %>%
  summarise(across(.cols = -stname, sum), .groups="drop") %>%
  mutate(stname=paste0(group, " sum")) %>%
  arrange(desc(stname))

tabdata <- bind_rows(tab1 %>% filter(group != "Remaining states"), tab2) 
tabdata  

dcols <- c("wtdsum_change_repeal", "wtdsum_change_reform", "change_change")
pcols <- c("change_share_repeal", "change_share_reform") #, "share_change")
ref <- html("SALT cap<br>raised to<br>$80,000")
tab <- tabdata %>%
  select(-group) %>%
  gt() %>%  
  tab_header(
    title = "Impact of raising the SALT cap versus full cap repeal",
    subtitle = paste0("Baseline is 2021 current law")
  ) %>%
  tab_spanner(label="Billions of dollars", 
              columns=contains("totchange")) %>%
  tab_spanner(label="Percentage", 
              columns=contains("share")) %>%
  cols_label(
      stname = "",
      totchange_repeal = "Full cap repeal",
      totchange_reform = ref,
      share_repeal="Full cap repeal",
      share_reform=ref
    ) %>%
  fmt_currency(
    columns = contains("totchange"),
    rows=1,
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  ) %>%
  fmt_number(
    columns = contains("totchange"),
    rows=2:nrow(tabdata),
    decimals = 1,
    scale_by = 1e-9,
    suffixing = FALSE
  ) %>%
  fmt_percent(
    columns = contains("share"),
    decimals = 1
  )
tab
# gtsave(tab, "USImpactReformVsRepeal_table.png", path = here::here(runresults), zoom=1.5, vwidth=1500)  # zoom 2 default
# gtsave(tab, "USImpactReformVsRepeal_table.png", path = here::here(runresults), zoom=2, vwidth=1500) 
gtsave(tab, "StatesImpactReformVsRepeal_table.png", path = here::here(runresults)) 
write_csv(tabdata, here::here(runresults, "StatesImpactReformVsRepeal_table_data.csv"))

```

